test:
    tags:
        - quartz
        - shell
    script:
        - cd rom
	- cp $CI_BUILDS_DIR/$CI_PROJECT_NAME/user.mk $CI_PROJECT_DIR/rom/user.mk
        - make LIBS_DIR=$CI_BUILDS_DIR/$CI_PROJECT_NAME/env
        - make merge LIBS_DIR=$CI_BUILDS_DIR/$CI_PROJECT_NAME/env
        - ./tests/runRegressionTests.sh
    allow_failure: true
