name: install-mfem

inputs:
  mfem-repo:
    description: 'Repo url for MFEM'
    required: false
    default: 'https://github.com/mfem/mfem.git'
  mfem-branch:
    description: 'Branch to checkout'
    required: true
  mfem-dir:
    description: 'MFEM top directory name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install MFEM
      run: |
        git clone --single-branch --branch ${{ inputs.mfem-branch }} --depth 1 ${{ inputs.mfem-repo }};
        cd mfem;
        make -j3 parallel;
        make info;
      shell: bash
